# Generated by Django 3.0.4 on 2020-03-27 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, unique=True, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Создатель',
                'verbose_name_plural': 'Создатели',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enable', models.BooleanField(default=True)),
                ('disabled_date', models.DateField(blank=True, null=True, verbose_name='Снят с публикации')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('description', models.TextField(max_length=400, verbose_name='Описание')),
                ('price', models.FloatField(verbose_name='Обычная цена')),
                ('discounted_price', models.FloatField(blank=True, null=True, verbose_name='Цена со скидкой')),
                ('video_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео')),
                ('category', models.ManyToManyField(to='market.Category', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='SalesStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold', models.IntegerField(verbose_name='Продажи')),
                ('amount', models.FloatField(verbose_name='Сумма')),
                ('in_stock', models.IntegerField(verbose_name='Товара в наличии')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.Creator', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Статистика продаж',
                'verbose_name_plural': 'Статистика продаж',
            },
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='products/', verbose_name='Загрузка фото')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.Product', verbose_name='Товар')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False, verbose_name='Заказ')),
                ('amount', models.FloatField(verbose_name='Сумма')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.Customer', verbose_name='Покупатель')),
                ('products', models.ManyToManyField(to='market.Product', verbose_name='Товары')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Mask',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='market.Product')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.Creator', verbose_name='Создатель маски')),
            ],
            options={
                'verbose_name': 'Маска',
                'verbose_name_plural': 'Маски',
            },
            bases=('market.product',),
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='market.Product')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.Creator', verbose_name='Создатель фильтра')),
            ],
            options={
                'verbose_name': 'Фильтр',
                'verbose_name_plural': 'Фильтры',
            },
            bases=('market.product',),
        ),
    ]
