# Generated by Django 3.0.4 on 2020-03-25 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, unique=True, verbose_name='Создатель')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Покупатель')),
            ],
        ),
        migrations.CreateModel(
            name='SalesStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False, verbose_name='Заказ')),
                ('sum', models.FloatField(verbose_name='Сумма')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Mask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enable', models.BooleanField(default=True, verbose_name='Доступна ли')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('description', models.TextField(max_length=400, verbose_name='Описание')),
                ('price', models.FloatField(verbose_name='Обычная цена')),
                ('discounted_price', models.FloatField(null=True, verbose_name='Цена со скидкой')),
                ('video_link', models.URLField(null=True, verbose_name='Ссылка на видео')),
                ('photo', models.ImageField(upload_to='masks/', verbose_name='Загрузка фото')),
                ('category', models.ManyToManyField(to='market.Category', verbose_name='Категория')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.Creator', verbose_name='Создатель маски')),
            ],
            options={
                'verbose_name': 'Маска',
                'verbose_name_plural': 'Маски',
            },
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enable', models.BooleanField(default=True, verbose_name='Доступен ли')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('description', models.TextField(max_length=400, verbose_name='Описание')),
                ('price', models.FloatField(verbose_name='Обычная цена')),
                ('discounted_price', models.FloatField(null=True, verbose_name='Цена со скидкой')),
                ('video_link', models.URLField(null=True, verbose_name='Ссылка на видео')),
                ('photo', models.ImageField(upload_to='filters/', verbose_name='Загрузка фото')),
                ('category', models.ManyToManyField(to='market.Category', verbose_name='Категория')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.Creator', verbose_name='Создатель фильтра')),
            ],
            options={
                'verbose_name': 'Фильтр',
                'verbose_name_plural': 'Фильтры',
            },
        ),
    ]
