# Generated by Django 3.0.4 on 2020-03-25 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='salesstatistic',
            options={'verbose_name': 'Статистика продаж'},
        ),
    ]
