# Generated by Django 3.0.4 on 2020-03-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mask',
            options={'verbose_name': 'Маску', 'verbose_name_plural': 'Маски'},
        ),
        migrations.AlterField(
            model_name='product',
            name='is_enable',
            field=models.BooleanField(default=True, verbose_name='Отображается'),
        ),
    ]
